a = int(input("please enter the first number:"))
b = int(input("please enter the second number:"))
c = int(input("please enter the third number:"))
average=(a+b+c/3)
print("the average of three number is",average)